## Import Pandas library

In [ ]:
import pandas as pd

## Import dataframe

In [ ]:
df_orig = pd.read_excel('Dataset.xlsx')
df_orig.head(5)

,Unnamed: 0,X,ID,Title,Year,Age,IMDb,Rotten.Tomatoes,Netflix,Hulu,Prime.Video,Disney.,Type,Directors,Genres,Country,Language,Runtime
0,1,0.0,1.0,Inception,2010.0,13+,8.8,0.87,1.0,0.0,0.0,0.0,0.0,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0
1,2,1.0,2.0,The Matrix,1999.0,18+,8.7,0.87,1.0,0.0,0.0,0.0,0.0,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0
2,3,2.0,3.0,Avengers: Infinity War,2018.0,13+,8.5,0.84,1.0,0.0,0.0,0.0,0.0,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0
3,4,3.0,4.0,Back to the Future,1985.0,7+,8.5,0.96,1.0,0.0,0.0,0.0,0.0,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0
4,5,4.0,5.0,"The Good, the Bad and the Ugly",1966.0,18+,8.8,0.97,1.0,0.0,1.0,0.0,0.0,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0

## Remove unnecessary columns

In [ ]:
df2 = df_orig.drop(columns=['Unnamed: 0', 'X', 'ID'])
df2.head(5)

,Title,Year,Age,IMDb,Rotten.Tomatoes,Netflix,Hulu,Prime.Video,Disney.,Type,Directors,Genres,Country,Language,Runtime
0,Inception,2010.0,13+,8.8,0.87,1.0,0.0,0.0,0.0,0.0,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0
1,The Matrix,1999.0,18+,8.7,0.87,1.0,0.0,0.0,0.0,0.0,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0
2,Avengers: Infinity War,2018.0,13+,8.5,0.84,1.0,0.0,0.0,0.0,0.0,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0
3,Back to the Future,1985.0,7+,8.5,0.96,1.0,0.0,0.0,0.0,0.0,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0
4,"The Good, the Bad and the Ugly",1966.0,18+,8.8,0.97,1.0,0.0,1.0,0.0,0.0,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0

## Convert original dataset to 1st Normal Form (1NF)

In [ ]:
#Convert Directors, Genres, Country, and Language columns to explodable format using split function
df2 = df2.assign(Directors=df2.Directors.str.split(","))
df2 = df2.assign(Genres=df2.Genres.str.split(","))
df2 = df2.assign(Country=df2.Country.str.split(","))
df2 = df2.assign(Language=df2.Language.str.split(","))
df2.head(5)

,Title,Year,Age,IMDb,Rotten.Tomatoes,Netflix,Hulu,Prime.Video,Disney.,Type,Directors,Genres,Country,Language,Runtime
0,Inception,2010.0,13+,8.8,0.87,1.0,0.0,0.0,0.0,0.0,[Christopher Nolan],"[Action, Adventure, Sci-Fi, Thriller]","[United States, United Kingdom]","[English, Japanese, French]",148.0
1,The Matrix,1999.0,18+,8.7,0.87,1.0,0.0,0.0,0.0,0.0,"[Lana Wachowski, Lilly Wachowski]","[Action, Sci-Fi]",[United States],[English],136.0
2,Avengers: Infinity War,2018.0,13+,8.5,0.84,1.0,0.0,0.0,0.0,0.0,"[Anthony Russo, Joe Russo]","[Action, Adventure, Sci-Fi]",[United States],[English],149.0
3,Back to the Future,1985.0,7+,8.5,0.96,1.0,0.0,0.0,0.0,0.0,[Robert Zemeckis],"[Adventure, Comedy, Sci-Fi]",[United States],[English],116.0
4,"The Good, the Bad and the Ugly",1966.0,18+,8.8,0.97,1.0,0.0,1.0,0.0,0.0,[Sergio Leone],[Western],"[Italy, Spain, West Germany]",[Italian],161.0

In [ ]:
#Explode dataframe
col_to_explode = ['Directors','Genres','Country','Language']

for i in col_to_explode:
    df2 = df2.explode(i)

#reset index
df2 = df2.reset_index()

#delete old index
df2 = df2.drop(['index'],axis=1)

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79971 entries, 0 to 79970
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Title            79969 non-null  object
 1   Year             79969 non-null  float64
 2   Age              43912 non-null  object
 3   IMDb             79969 non-null  float64
 4   Rotten.Tomatoes  37500 non-null  float64
 5   Netflix          79969 non-null  float64
 6   Hulu             79969 non-null  float64
 7   Prime.Video      79969 non-null  float64
 8   Disney.          79969 non-null  float64
 9   Type             79969 non-null  float64
 10  Directors        78887 non-null  object
 11  Genres           79936 non-null  object
 12  Country          79743 non-null  object
 13  Language         79360 non-null  object
 14  Runtime          79969 non-null  float64
dtypes: float64(9), object(6)
memory usage: 9.2+ MB

In [ ]:
df2

,Title,Year,Age,IMDb,Rotten.Tomatoes,Netflix,Hulu,Prime.Video,Disney.,Type,Directors,Genres,Country,Language,Runtime
0,Inception,2010.0,13+,8.8,0.87,1.0,0.0,0.0,0.0,0.0,Christopher Nolan,Action,United States,English,148.0
1,Inception,2010.0,13+,8.8,0.87,1.0,0.0,0.0,0.0,0.0,Christopher Nolan,Action,United States,Japanese,148.0
2,Inception,2010.0,13+,8.8,0.87,1.0,0.0,0.0,0.0,0.0,Christopher Nolan,Action,United States,French,148.0
3,Inception,2010.0,13+,8.8,0.87,1.0,0.0,0.0,0.0,0.0,Christopher Nolan,Action,United Kingdom,English,148.0
4,Inception,2010.0,13+,8.8,0.87,1.0,0.0,0.0,0.0,0.0,Christopher Nolan,Action,United Kingdom,Japanese,148.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79966,The Poof Point,2001.0,7+,4.7,NaN,0.0,0.0,0.0,1.0,0.0,Neal Israel,Comedy,United States,English,90.0
79967,The Poof Point,2001.0,7+,4.7,NaN,0.0,0.0,0.0,1.0,0.0,Neal Israel,Family,United States,English,90.0
79968,The Poof Point,2001.0,7+,4.7,NaN,0.0,0.0,0.0,1.0,0.0,Neal Israel,Sci-Fi,United States,English,90.0
79969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Export new data to Excel

In [ ]:
df2.to_excel('Movie_Dataset_Updated.xlsx',sheet_name='Movie_Dataset_Updated',index=False)